ProyectoTFG/ProyectoTFG/Models/Menu.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace ProyectoTFG.Models
{
    public class Menu
    {

        public int ID { get; set; }

        [Required]
        public string Controller { get; set; }

        [Required]
        public string Action { get; set; }

        [Required]
        public string Label { get; set; }

        [InverseProperty("Menu")]
        public List<RoleHasMenu> ListRoleHasMenu { get; set; }

        [NotMapped]
        public string Fullname
        {
            get => (Controller + " - " + Action);
        }

    }
}

ProyectoTFG/ProyectoTFG/Controllers/MenusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProyectoTFG.Data;
using ProyectoTFG.Filters;
using ProyectoTFG.Models;

namespace ProyectoTFG.Controllers
{
    [ServiceFilter(typeof(VerificaSesion))]
    [ServiceFilter(typeof(VerificaAdmin))]
    public class MenusController : Controller
    {
        private readonly MiDbContext _context;

        public static List<Menu> Menus { get; set; } = new List<Menu>();

        public MenusController(MiDbContext context)
        {
            _context = context;
        }

        // GET: Menus
        //public async Task<IActionResult> Index()
        //{
        //    return View(await _context.Menu.ToListAsync());
        //}

        public async Task<IActionResult> Index(String busqueda)
        {
            var miDbContext = _context.Menu.OrderBy(m => m.Controller);
            try
            {
                if (busqueda != null)
                {

                    miDbContext = _context.Menu.Where(n => n.Controller == busqueda).OrderBy(m => m.Controller);
                }
            }
            catch (FormatException e)
            {
                TempData["ErrorMessage"] = "El formato de texto no es correcto.";
                return RedirectToAction(nameof(Index));
            }
            return View(await miDbContext.ToListAsync());
        }

        // GET: Menus/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var menu = await _context.Menu
                .FirstOrDefaultAsync(m => m.ID == id);
            if (menu == null)
            {
                return NotFound();
            }

            return View(menu);
        }

        // GET: Menus/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Menus/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Controller,Action,Label")] Menu menu)
        {
            if (ModelState.IsValid)
            {
                _context.Add(menu);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(menu);
        }

        // GET: Menus/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var menu = await _context.Menu.FindAsync(id);
            if (menu == null)
            {
                return NotFound();
            }
            return View(menu);
        }

        // POST: Menus/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Controller,Action,Label")] Menu menu)
        {
            if (id != menu.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(menu);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MenuExists(menu.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(menu);
        }

        // GET: Menus/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var menu = await _context.Menu
                .FirstOrDefaultAsync(m => m.ID == id);
            if (menu == null)
            {
                return NotFound();
            }

            return View(menu);
        }

        // POST: Menus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var menu = await _context.Menu.FindAsync(id);
            _context.Menu.Remove(menu);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MenuExists(int id)
        {
            return _context.Menu.Any(e => e.ID == id);
        }
    }
}

ProyectoTFG/ProyectoTFG/Views/Menus/Create.cshtml
@model ProyectoTFG.Models.Menu

@{
    ViewData["Title"] = "Create";
}

<div class="card mt-5" style="padding: 50px; color: black">
    <h1>Create</h1>

    <h4>Menu</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Controller" class="control-label"></label>
                    <input asp-for="Controller" class="form-control" />
                    <span asp-validation-for="Controller" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Action" class="control-label"></label>
                    <input asp-for="Action" class="form-control" />
                    <span asp-validation-for="Action" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Label" class="control-label"></label>
                    <input asp-for="Label" class="form-control" />
                    <span asp-validation-for="Label" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />

                    <a class="btn btn-danger" asp-action="Index">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-left-circle-fill" viewBox="0 0 16 16">
                            <path d="M8 0a8 8 0 1 0 0 16A8 8 0 0 0 8 0zm3.5 7.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z" />
                        </svg>
                        Back
                    </a>
                </div>
            </form>
        </div>
    </div>
</div>

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }

ProyectoTFG/ProyectoTFG/Views/Menus/Delete.cshtml
@model ProyectoTFG.Models.Menu

@{
    ViewData["Title"] = "Delete";
}

<div class="card mt-5" style="padding: 50px; color: black">
    <h1>Delete</h1>

    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Menu</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Controller)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Controller)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Action)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Action)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Label)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Label)
            </dd>
        </dl>

        <form asp-action="Delete">
            <input type="hidden" asp-for="ID" />
            <input type="submit" value="Delete" class="btn btn-danger" />

            <a class="btn btn-info" asp-action="Index">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-left-circle-fill" viewBox="0 0 16 16">
                    <path d="M8 0a8 8 0 1 0 0 16A8 8 0 0 0 8 0zm3.5 7.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z" />
                </svg>
                Back
            </a>
        </form>
    </div>
</div>

ProyectoTFG/ProyectoTFG/Views/Menus/Details.cshtml
@model ProyectoTFG.Models.Menu

@{
    ViewData["Title"] = "Details";
}

<div class="card mt-5" style="padding: 50px; color: black">
    <h1>Details</h1>

    <div>
        <h4>Menu</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Controller)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Controller)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Action)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Action)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Label)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Label)
            </dd>
        </dl>
    </div>
    <div>
        <a class="btn btn-success" asp-action="Edit" asp-route-id="@Model.ID">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-fill" viewBox="0 0 16 16">
                <path d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z" />
            </svg>
        </a>

        <a class="btn btn-danger" asp-action="Index">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-left-circle-fill" viewBox="0 0 16 16">
                <path d="M8 0a8 8 0 1 0 0 16A8 8 0 0 0 8 0zm3.5 7.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z" />
            </svg>
            Back
        </a>
    </div>
</div>

ProyectoTFG/ProyectoTFG/Views/Menus/Edit.cshtml
@model ProyectoTFG.Models.Menu

@{
    ViewData["Title"] = "Edit";
}

<div class="card mt-5" style="padding: 50px; color: black">
    <h1>Edit</h1>

    <h4>Menu</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="ID" />
                <div class="form-group">
                    <label asp-for="Controller" class="control-label"></label>
                    <input asp-for="Controller" class="form-control" />
                    <span asp-validation-for="Controller" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Action" class="control-label"></label>
                    <input asp-for="Action" class="form-control" />
                    <span asp-validation-for="Action" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Label" class="control-label"></label>
                    <input asp-for="Label" class="form-control" />
                    <span asp-validation-for="Label" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary" />

                    <a class="btn btn-danger" asp-action="Index">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-left-circle-fill" viewBox="0 0 16 16">
                            <path d="M8 0a8 8 0 1 0 0 16A8 8 0 0 0 8 0zm3.5 7.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z" />
                        </svg>
                        Back
                    </a>
                </div>
            </form>
        </div>
    </div>
</div>

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }

ProyectoTFG/ProyectoTFG/Views/Menus/Index.cshtml
@model IEnumerable<ProyectoTFG.Models.Menu>

@{
    ViewData["Title"] = "Index";
}

<div class="card mt-5" style="padding: 50px">
    <h1 style="color: black">Menus</h1>

    <p>
        <a asp-action="Create">Create New</a>
    </p>

    <form class="mb-3" asp-controller="Menus" asp-action="Index" method="get">
        <div class="input-group">
            <button class="btn btn-warning" type="submit">Controller</button>
            <input type="text" name="busqueda" class="form-control" placeholder="Example 'Admins'">
        </div>
        <a class="btn btn-danger m-1" asp-page="/Index">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-left-circle-fill" viewBox="0 0 16 16">
                <path d="M8 0a8 8 0 1 0 0 16A8 8 0 0 0 8 0zm3.5 7.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z" />
            </svg>
            Back to List
        </a>
    </form>

    <table class="table table-dark table-striped">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Controller)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Action)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Label)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Controller)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Action)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Label)
                    </td>
                    <td class="btn-group">
                        <a class="btn btn-success" asp-action="Edit" asp-route-id="@item.ID">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-fill" viewBox="0 0 16 16">
                                <path d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z" />
                            </svg>
                        </a>
                        <a class="btn btn-primary" asp-action="Details" asp-route-id="@item.ID">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-journal-medical" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M8 4a.5.5 0 0 1 .5.5v.634l.549-.317a.5.5 0 1 1 .5.866L9 6l.549.317a.5.5 0 1 1-.5.866L8.5 6.866V7.5a.5.5 0 0 1-1 0v-.634l-.549.317a.5.5 0 1 1-.5-.866L7 6l-.549-.317a.5.5 0 0 1 .5-.866l.549.317V4.5A.5.5 0 0 1 8 4zM5 9.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5zm0 2a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5z" />
                                <path d="M3 0h10a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2v-1h1v1a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H3a1 1 0 0 0-1 1v1H1V2a2 2 0 0 1 2-2z" />
                                <path d="M1 5v-.5a.5.5 0 0 1 1 0V5h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1zm0 3v-.5a.5.5 0 0 1 1 0V8h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1zm0 3v-.5a.5.5 0 0 1 1 0v.5h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1z" />
                            </svg>
                        </a>
                        <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.ID">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3-fill" viewBox="0 0 16 16">
                                <path d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5Zm-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5ZM4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06Zm6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528ZM8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5Z" />
                            </svg>
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>