ProyectoTFG/ProyectoTFG/Models/Booking.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace ProyectoTFG.Models
{
    public class Booking
    {
        public int ID { get; set; }

        [DataType(DataType.Date)]
        public DateTime BookingDate { get; set; }

        public int MemberID { get; set; }

        [ForeignKey("MemberID")]
        public Member Member { get; set; }

        public int LibraryID { get; set; }

        [ForeignKey("LibraryID")]
        public Library Library { get; set; }

        public int BookID { get; set; }

        [ForeignKey("BookID")]
        public Book Book { get; set; }

        public int ZoneID { get; set; }

        [ForeignKey("ZoneID")]
        public Zone Zone { get; set; }

        public int TableID { get; set; }

        [ForeignKey("TableID")]
        public Table Table { get; set; }
    }
}

ProyectoTFG/ProyectoTFG/Controllers/BookingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProyectoTFG.Data;
using ProyectoTFG.Filters;
using ProyectoTFG.Models;

namespace ProyectoTFG.Controllers
{
    [ServiceFilter(typeof(VerificaSesion))]
    [ServiceFilter(typeof(VerificaAdmin))]
    public class BookingsController : Controller
    {
        private readonly MiDbContext _context;

        public BookingsController(MiDbContext context)
        {
            _context = context;
        }

        // GET: Bookings
        //public async Task<IActionResult> Index()
        //{
        //    var miDbContext = _context.Bookings.Include(b => b.Book).Include(b => b.Library).Include(b => b.Member).Include(b => b.Table).Include(b => b.Zone);
        //    return View(await miDbContext.ToListAsync());
        //}
        public async Task<IActionResult> Index(String busqueda)
        {
            var miDbContext = _context.Bookings.Include(b => b.Book).Include(b => b.Library).Include(b => b.Member).Include(b => b.Table).Include(b => b.Zone).OrderBy(b => b.BookingDate);
            try
            {
                if (busqueda != null)
                {

                    miDbContext = _context.Bookings.Include(b => b.Book).Include(b => b.Library).Include(b => b.Member).Include(b => b.Table).Include(b => b.Zone).Where(f => f.BookingDate >= DateTime.Parse(busqueda)).OrderBy(b => b.BookingDate);
                }
            }
            catch (FormatException e)
            {
                TempData["ErrorMessage"] = "El formato de fecha no es correcto.";
                return RedirectToAction(nameof(Index));
            }
            return View(await miDbContext.ToListAsync());
        }

        // GET: Bookings/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var booking = await _context.Bookings
                .Include(b => b.Book)
                .Include(b => b.Library)
                .Include(b => b.Member)
                .Include(b => b.Table)
                .Include(b => b.Zone)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (booking == null)
            {
                return NotFound();
            }

            return View(booking);
        }

        // GET: Bookings/Create
        public IActionResult Create()
        {
            ViewData["BookID"] = new SelectList(_context.Books, "ID", "Name");
            ViewData["LibraryID"] = new SelectList(_context.Libraries, "ID", "Name");
            ViewData["MemberID"] = new SelectList(_context.Members, "ID", "Name");
            ViewData["TableID"] = new SelectList(_context.Tables, "ID", "NumberTable");
            ViewData["ZoneID"] = new SelectList(_context.Zones, "ID", "ID");
            return View();
        }

        // POST: Bookings/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,BookingDate,MemberID,LibraryID,BookID,ZoneID,TableID")] Booking booking)
        {
            if (ModelState.IsValid)
            {
                var bookLibrary = _context.Books.Where(b => b.ID == booking.BookID && b.LibraryID == booking.LibraryID).FirstOrDefault();

                if(bookLibrary == null)
                {
                    TempData["errorMessage"] = "El Libro no pertenece a esa Biblioteca";
                    return RedirectToAction(nameof(Create));
                }

                var zoneLibrary = _context.Zones.Where(z => z.ID == booking.ZoneID && z.LibraryID == booking.LibraryID).FirstOrDefault();

                if (zoneLibrary == null)
                {
                    TempData["errorMessage"] = "La Zona no pertenece a esa Biblioteca";
                    return RedirectToAction(nameof(Create));
                }

                var tableLibrary = _context.Tables.Include(t => t.Zone).Where(t => t.ID == booking.TableID && t.Zone.LibraryID == booking.LibraryID && t.ZoneID == booking.ZoneID).FirstOrDefault();

                if (tableLibrary == null)
                {
                    TempData["errorMessage"] = "La Mesa no pertenece a esa Biblioteca o a esa Zona";
                    return RedirectToAction(nameof(Create));
                }

                var bookingFecha = _context.Bookings.Where(b => b.BookingDate == booking.BookingDate &&
                (b.BookID == booking.BookID || b.TableID == booking.TableID)).FirstOrDefault();

                if(bookingFecha != null)
                {
                    TempData["errorMessage"] = "Ya está siendo usado el Libro o la Mesa en esa fecha";
                    return RedirectToAction(nameof(Create));
                }

                _context.Add(booking);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["BookID"] = new SelectList(_context.Books, "ID", "Name", booking.BookID);
            ViewData["LibraryID"] = new SelectList(_context.Libraries, "ID", "Name", booking.LibraryID);
            ViewData["MemberID"] = new SelectList(_context.Members, "ID", "Name", booking.MemberID);
            ViewData["TableID"] = new SelectList(_context.Tables, "ID", "NumberTable", booking.TableID);
            ViewData["ZoneID"] = new SelectList(_context.Zones, "ID", "ID", booking.ZoneID);
            return View(booking);
        }

        // GET: Bookings/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var booking = await _context.Bookings.FindAsync(id);
            if (booking == null)
            {
                return NotFound();
            }
            ViewData["BookID"] = new SelectList(_context.Books, "ID", "Name", booking.BookID);
            ViewData["LibraryID"] = new SelectList(_context.Libraries, "ID", "Name", booking.LibraryID);
            ViewData["MemberID"] = new SelectList(_context.Members, "ID", "Name", booking.MemberID);
            ViewData["TableID"] = new SelectList(_context.Tables, "ID", "NumberTable", booking.TableID);
            ViewData["ZoneID"] = new SelectList(_context.Zones, "ID", "Description", booking.ZoneID);
            return View(booking);
        }

        // POST: Bookings/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,BookingDate,MemberID,LibraryID,BookID,ZoneID,TableID")] Booking booking)
        {
            if (id != booking.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {

                    var bookLibrary = _context.Books.Where(b => b.ID == booking.BookID && b.LibraryID == booking.LibraryID).FirstOrDefault();

                    if (bookLibrary == null)
                    {
                        TempData["errorMessage"] = "El Libro no pertenece a esa Biblioteca";
                        return RedirectToAction(nameof(Edit));
                    }

                    var zoneLibrary = _context.Zones.Where(z => z.ID == booking.ZoneID && z.LibraryID == booking.LibraryID).FirstOrDefault();

                    if (zoneLibrary == null)
                    {
                        TempData["errorMessage"] = "La Zona no pertenece a esa Biblioteca";
                        return RedirectToAction(nameof(Edit));
                    }

                    var tableLibrary = _context.Tables.Include(t => t.Zone).Where(t => t.ID == booking.TableID && t.Zone.LibraryID == booking.LibraryID).FirstOrDefault();

                    if (tableLibrary == null)
                    {
                        TempData["errorMessage"] = "La Mesa no pertenece a esa Biblioteca o a esa Zona";
                        return RedirectToAction(nameof(Edit));
                    }

                    var bookingFecha = _context.Bookings.Where(b => b.BookingDate == booking.BookingDate &&
                    (b.BookID == booking.BookID || b.TableID == booking.TableID)).FirstOrDefault();

                    if (bookingFecha != null)
                    {
                        TempData["errorMessage"] = "Ya está siendo usado el Libro o la Mesa en esa fecha";
                        return RedirectToAction(nameof(Create));
                    }

                    _context.Update(booking);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookingExists(booking.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            
            ViewData["BookID"] = new SelectList(_context.Books, "ID", "Name", booking.BookID);
            ViewData["LibraryID"] = new SelectList(_context.Libraries, "ID", "Name", booking.LibraryID);
            ViewData["MemberID"] = new SelectList(_context.Members, "ID", "Name", booking.MemberID);
            ViewData["TableID"] = new SelectList(_context.Tables, "ID", "NumberTable", booking.TableID);

ProyectoTFG/ProyectoTFG/Views/Bookings/Create.cshtml
@model ProyectoTFG.Models.Booking


@{
    ViewData["Title"] = "Create";
}

<div class="card mt-5" style="padding: 50px; color: black">
    <h1>Create</h1>

    <h4>Booking</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="BookingDate" class="control-label"></label>
                    <input asp-for="BookingDate" class="form-control" />
                    <span asp-validation-for="BookingDate" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="LibraryID" class="control-label"></label>
                    <select asp-for="LibraryID" class="form-control" asp-items="ViewBag.LibraryID"></select>
                </div>
                <div class="form-group">
                    <label asp-for="MemberID" class="control-label"></label>
                    <select asp-for="MemberID" class="form-control" asp-items="ViewBag.MemberID"></select>
                </div>

                <div class="form-group">
                    <label asp-for="ZoneID" class="control-label"></label>
                    <select asp-for="ZoneID" class="form-control" asp-items="ViewBag.ZoneID"></select>
                </div>

                <div class="form-group">
                    <label asp-for="TableID" class="control-label"></label>
                    <select asp-for="TableID" class="form-control" asp-items="ViewBag.TableID"></select>
                </div>

                <div class="form-group">
                    <label asp-for="BookID" class="control-label"></label>
                    <select asp-for="BookID" class="form-control" asp-items="ViewBag.BookID"></select>
                </div>


                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />

                    <a class="btn btn-danger" asp-action="Index">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-left-circle-fill" viewBox="0 0 16 16">
                            <path d="M8 0a8 8 0 1 0 0 16A8 8 0 0 0 8 0zm3.5 7.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z" />
                        </svg>
                        Back
                    </a>
                </div>
            </form>
        </div>
    </div>

    @if (TempData["errorMessage"] != null)
    {
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            @TempData["errorMessage"]
            <button type="button" class="close" data-dismiss="alert" aria-label="close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    }

</div>

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }

ProyectoTFG/ProyectoTFG/Views/Bookings/Delete.cshtml
@model ProyectoTFG.Models.Booking

@{
    ViewData["Title"] = "Delete";
}

<div class="card mt-5" style="padding: 50px; color: black">
    <h1>Delete</h1>

    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Booking</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.BookingDate)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.BookingDate)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Member)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Member.Address)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Library)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Library.Address)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Book)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Book.Author)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Zone)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Zone.Description)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Table)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Table.ID)
            </dd>
        </dl>

        <form asp-action="Delete">
            <input type="hidden" asp-for="ID" />
            <input type="submit" value="Delete" class="btn btn-danger" />


            <a class="btn btn-info" asp-action="Index">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-left-circle-fill" viewBox="0 0 16 16">
                    <path d="M8 0a8 8 0 1 0 0 16A8 8 0 0 0 8 0zm3.5 7.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z" />
                </svg>
                Back
            </a>
        </form>
    </div>
</div>

ProyectoTFG/ProyectoTFG/Views/Bookings/Details.cshtml
@model ProyectoTFG.Models.Booking

@{
    ViewData["Title"] = "Details";
}

<div class="card mt-5" style="padding: 50px; color: black">
    <h1>Details</h1>

    <div>
        <h4>Booking</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.BookingDate)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.BookingDate)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Member)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Member.Name)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Library)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Library.Name)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Book)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Book.Name)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Zone)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Zone.Description)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Table)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Table.NumberTable)
            </dd>
        </dl>
    </div>
    <div>
        <a class="btn btn-success" asp-action="Edit" asp-route-id="@Model.ID">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-fill" viewBox="0 0 16 16">
                <path d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z" />
            </svg>
        </a>

        <a class="btn btn-danger" asp-action="Index">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-left-circle-fill" viewBox="0 0 16 16">
                <path d="M8 0a8 8 0 1 0 0 16A8 8 0 0 0 8 0zm3.5 7.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z" />
            </svg>
            Back
        </a>
    </div>
</div>

ProyectoTFG/ProyectoTFG/Views/Bookings/Edit.cshtml
@model ProyectoTFG.Models.Booking

@{
    ViewData["Title"] = "Edit";
}

<div class="card mt-5" style="padding: 50px; color: black">
    <h1>Edit</h1>

    <h4>Booking</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="ID" />
                <div class="form-group">
                    <label asp-for="BookingDate" class="control-label"></label>
                    <input asp-for="BookingDate" class="form-control" />
                    <span asp-validation-for="BookingDate" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="MemberID" class="control-label"></label>
                    <select asp-for="MemberID" class="form-control" asp-items="ViewBag.MemberID"></select>
                    <span asp-validation-for="MemberID" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="LibraryID" class="control-label"></label>
                    <select asp-for="LibraryID" class="form-control" asp-items="ViewBag.LibraryID"></select>
                    <span asp-validation-for="LibraryID" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="BookID" class="control-label"></label>
                    <select asp-for="BookID" class="form-control" asp-items="ViewBag.BookID"></select>
                    <span asp-validation-for="BookID" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ZoneID" class="control-label"></label>
                    <select asp-for="ZoneID" class="form-control" asp-items="ViewBag.ZoneID"></select>
                    <span asp-validation-for="ZoneID" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="TableID" class="control-label"></label>
                    <select asp-for="TableID" class="form-control" asp-items="ViewBag.TableID"></select>
                    <span asp-validation-for="TableID" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary" />

                    <a class="btn btn-danger" asp-action="Index">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-left-circle-fill" viewBox="0 0 16 16">
                            <path d="M8 0a8 8 0 1 0 0 16A8 8 0 0 0 8 0zm3.5 7.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z" />
                        </svg>
                        Back
                    </a>
                </div>
            </form>
        </div>
    </div>
</div>

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }

ProyectoTFG/ProyectoTFG/Views/Bookings/Index.cshtml
@model IEnumerable<ProyectoTFG.Models.Booking>

@{
    ViewData["Title"] = "Index";
}

<div class="card mt-5" style="padding: 50px">
    <h1 style="color: black">Bookings</h1>

    <p>
        <a asp-action="Create">Create New</a>
    </p>

    <form asp-controller="Bookings" asp-action="Index" method="get">

        <div class="input-group mb-3">
            <button class="btn btn-warning" type="submit">Filter by date</button>
            <input type="date" name="busqueda" class="form-control" placeholder="Example yyyy/MM/dd">
        </div>
        <a class="btn btn-danger m-1" asp-page="/Index">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-left-circle-fill" viewBox="0 0 16 16">
                <path d="M8 0a8 8 0 1 0 0 16A8 8 0 0 0 8 0zm3.5 7.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z" />
            </svg>
            Back to List
        </a>
    </form>

    <table class="table table-dark table-striped">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.BookingDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Member)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Library)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Book)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Zone)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Table)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.BookingDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Member.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Library.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Book.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Zone.Description)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Table.NumberTable)
                    </td>
                    <td class="btn-group">
                        <a class="btn btn-success" asp-action="Edit" asp-route-id="@item.ID">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-fill" viewBox="0 0 16 16">
                                <path d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z" />
                            </svg>
                        </a>
                        <a class="btn btn-primary" asp-action="Details" asp-route-id="@item.ID">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-journal-medical" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M8 4a.5.5 0 0 1 .5.5v.634l.549-.317a.5.5 0 1 1 .5.866L9 6l.549.317a.5.5 0 1 1-.5.866L8.5 6.866V7.5a.5.5 0 0 1-1 0v-.634l-.549.317a.5.5 0 1 1-.5-.866L7 6l-.549-.317a.5.5 0 0 1 .5-.866l.549.317V4.5A.5.5 0 0 1 8 4zM5 9.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5zm0 2a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5z" />
                                <path d="M3 0h10a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2v-1h1v1a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H3a1 1 0 0 0-1 1v1H1V2a2 2 0 0 1 2-2z" />
                                <path d="M1 5v-.5a.5.5 0 0 1 1 0V5h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1zm0 3v-.5a.5.5 0 0 1 1 0V8h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1zm0 3v-.5a.5.5 0 0 1 1 0v.5h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1z" />
                            </svg>
                        </a>
                        <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.ID">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3-fill" viewBox="0 0 16 16">
                                <path d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5Zm-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5ZM4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06Zm6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528ZM8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5Z" />
                            </svg>
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>